### ISSUE TITLE
new-release-published was false even though a release was generated

### ISSUE THREAD

**Issue by LukeHersman** [felipecrs/semantic-release-export-data#8]
Hi! Trying to use this and I think I have it set up correctly:

Added to package.json
`"plugins": [
            "semantic-release-export-data",...`

Job:
```
    getNextVersion:
      name: Get next semantic-release version
      runs-on: ubuntu-latest
      permissions:
        contents: write
        issues: write
        pull-requests: write
      steps:
        - uses: actions/checkout@master

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
              node-version: 20
              registry-url: https://npm.pkg.github.com/
              scope: '@companyScope'

        - name: Install dependencies
          run: npm ci
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

        - name: Install semantic-release extra plugins
          run: npm install --save-dev @semantic-release/changelog @semantic-release/git semantic-release-export-data

        - run: npx semantic-release --dry-run
          id: getNextVersion
          env:
            GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      outputs:
        newReleasePublished: ${{ steps.getNextVersion.outputs.newReleasePublished }}
        newReleaseVersion: ${{ steps.getNextVersion.outputs.newReleaseVersion }}
```

trying to use the `newReleasePublished` variable

```
    buildLinuxScan:
        name: Build Linux & Scan
        runs-on: ubuntu-latest
        needs: getNextVersion
        permissions:
            contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://npm.pkg.github.com/
                  scope: '@companyScope'

            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
            ...

            - name: Edit version number in place
              if: needs.getNextVersion.outputs.newReleasePublished == 'true'
              shell: bash
              run: |
                echo $(jq --arg a "${{ needs.getNextVersion.outputs.newReleaseVersion }}" '.version = ($a)' package.json) > package.json 
```

The `Edit version number in place` step was skipped (as in `newReleasePublished` was `false` or null) even though a release was ultimately generated.  Here's the logs from the `getNextVersion` job

```
[1:56:34 PM] [semantic-release] › ℹ  Running semantic-release version 23.0.0
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-export-data"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "semantic-release-export-data"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[1:56:34 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[1:56:36 PM] [semantic-release] › ⚠  Run automated release from branch develop on repository https://github.com/{repoURL} in dry-run modehttps://github.com/{repoURL}
[1:56:36 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[1:56:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-export-data"
[1:56:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-export-data"
[1:56:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[1:56:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[1:56:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[1:56:36 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[1:56:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[1:56:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[1:56:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[1:56:36 PM] [semantic-release] › ℹ  Found git tag v1.0.0-beta.2 associated with version 1.0.0-beta.2 on branch develop
[1:56:36 PM] [semantic-release] › ℹ  Found 2 commits since last release
[1:56:36 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[1:56:36 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(build): fixed token and permissions (#1[9](https://github.com/{repoURL}/actions/runs/9483920740/job/26132193190#step:6:10))
[1:56:36 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[1:56:36 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(build): passing in next version to build so artifact version is c… (#18)

**_[lots of commits listed, omitting for length]_**

[1:56:36 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[1:56:36 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[1:56:36 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[1:56:36 PM] [semantic-release] › ℹ  The next release version is 1.0.0-beta.3
[1:56:36 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "semantic-release-export-data"
[1:56:36 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "semantic-release-export-data"
[1:56:36 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[1:56:36 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[1:56:36 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
[1:56:36 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
[1:56:36 PM] [semantic-release] › ⚠  Skip v1.0.0-beta.3 tag creation in dry-run mode
[1:56:36 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[1:56:36 PM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[1:56:36 PM] [semantic-release] › ✔  Published release 1.0.0-beta.3 on beta channel
[1:56:36 PM] [semantic-release] › ℹ  Release note for version 1.0.0-beta.3:
# 1.0.0-beta.3 (https://github.com/{repoURL}/compare/v1.0.0-beta.2...v1.0.0-beta.3) (2024-06-12)

### Bug Fixes

**_[notes were listed, omitted for length]_**
```
